<a href="https://colab.research.google.com/github/sujalkyal/google-colab-saves/blob/practice/Word_Embedding_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [4]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [5]:
#vocabulary size
voc_size=500

#One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[65, 58, 121, 74, 36, 371], [414, 439, 121, 220, 165, 362], [402, 424, 188, 478], [65, 243, 121, 425, 65, 310], [443, 270, 279, 121, 220, 165, 362], [6, 121, 220, 165, 484, 126]]


In [7]:
#word embedding

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
#pre_padding

In [11]:
sent_len=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[  0   0  65  58 121  74  36 371]
 [  0   0 414 439 121 220 165 362]
 [  0   0   0   0 402 424 188 478]
 [  0   0  65 243 121 425  65 310]
 [  0 443 270 279 121 220 165 362]
 [  0   0   6 121 220 165 484 126]]


In [12]:
# setting 10 feature dimention
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_len))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
embedded_docs[0]

array([  0,   0,  65,  58, 121,  74,  36, 371], dtype=int32)

In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 121ms/step


array([[[ 0.02487017,  0.04273403, -0.01274756, -0.02426685,
         -0.02024313, -0.01110066,  0.02005703, -0.01066753,
          0.02561654,  0.00282885],
        [ 0.02487017,  0.04273403, -0.01274756, -0.02426685,
         -0.02024313, -0.01110066,  0.02005703, -0.01066753,
          0.02561654,  0.00282885],
        [-0.02310524, -0.0410478 ,  0.02308995, -0.01785631,
         -0.04840033,  0.0067088 , -0.04359486, -0.03789448,
          0.01199474,  0.00368556],
        [ 0.0052215 , -0.00268054, -0.0042266 , -0.0263898 ,
          0.01507543, -0.03351624,  0.03389252, -0.03724999,
         -0.01533749,  0.03357284],
        [-0.00615451,  0.00391316,  0.01996925, -0.02560583,
         -0.02755623,  0.01411457, -0.01889824,  0.04762879,
          0.02960062, -0.03922523],
        [ 0.01092114,  0.01565157, -0.04992902,  0.03944871,
          0.02585829,  0.01232004,  0.04820449, -0.0170198 ,
         -0.03310709, -0.04470436],
        [-0.01002789, -0.01204186, -0.01477163,  0.0